### PR TITLE
I -sort- of see what you did there 🧐

### PR DESCRIPTION
**Pull request by jesseleite**
Based on the output you are trying to show, I think you sort of wanted `desc` in there?

### CODE REVIEW

**Comment by jackmcdade** [comment]
🥁 💥

**Comment by jesseleite** [comment]
On this note, a quick question...  The doc says modifier params are separated by `|` pipes:



But the sort modifier separates it's params via `:` a colon?

**Comment by jackmcdade** [comment]
Technically... it's an argument of a parameter.

```
modifier="param1:arg1|param2:arg1"
```

**Comment by jesseleite** [comment]
Gotcha! 👌

**Pull request merged**
