### PR TITLE
Update debugging.md

### PR DESCRIPTION
**Pull request by dannyuk1982**
Added in instructions on how to setup logging to Slack

### CODE REVIEW

**Review by jackmcdade — CHANGES_REQUESTED** [review]
I don't think we need instructions on how to create a Slack team or channel. Would you be up for taking a stab at explaining each key INSIDE the doc block, as comments? Super terse, as few words as possible. If not, I can do it.

**Comment by dannyuk1982** [comment]
Yup sure - I, personally, took ages to work out what a team was, what a channel was etc. if you have no idea what Slack is - it really isn't obvious, esp the terminology.

**Comment by jackmcdade** [comment]
True, but if you don't know what Slack is, you probably shouldn't be using it for Logging.

**Review by dannyuk1982 — COMMENTED** [review]
edited - much shorted now

**Comment by dannyuk1982** [comment]
" if you don't know what Slack is, you probably shouldn't be using it for Logging." Disagree, it's really useful - I find this a lot when trying to learn new stuff in the web-dev world, everything feels a bit like you should already know what you are doing (a bit elitist?) - and docs always seem to assume this, so actually learning what to do seems way harder than it needs to be. 

I actually set up a slack team, user, and channel just to log for a site - and it's great, but it could have been way simpler to do with a bit more instruction.

**Pull request merged**
