### PR TITLE
Path to redactor settings appears incorrect in docs.

### PR DESCRIPTION
**Pull request by Chris-May**
I've been trying to customize redactor based on documentation, and while there is a file at the location, it does nothing to redactor.

### CODE REVIEW

**Comment by jackmcdade** [comment]
You shouldn't edit default statamic files. They'll get overwritten every time you update.

**Comment by Chris-May** [comment]
Crap.
Editing where the docs say to didn't result in any changes.

**Comment by jasonvarga** [comment]
Open up a bug report over on https://github.com/statamic/v2-hub and we'll sort you out.

**Comment by Chris-May** [comment]
AH! But editing in the CP _does_ adjust the .yaml file from the documentation.

Thanks for the quick response, guys. I will check my code next week, and then report the bug at the url mentioned..

**Pull request closed without merging**
