### PR TITLE
add `auth.login` and `auth.logout` events

### PR DESCRIPTION
**Pull request by rrelmy**

### CODE REVIEW

**Comment by jasonvarga** [comment]
Have been debating this. These are Laravel events. Then do we have to document all of them?

I think a better solution is to explain that all Laravel events are also available.

**Comment by rrelmy** [comment]
I understand, for people not too familiar with Laravel this is not clear.
A quick overview what Laravel events are available would be nice I think.

## Laravel Events

| Event | Description |
| --- | --- |
| `auth.login` | On user login |
| `auth.logout` | ... |

**Comment by jasonvarga** [comment]
I think we can just link to https://laravel.com/docs/5.1/events#framework-events

**Comment by rrelmy** [comment]
Yes, but this overview does no longer exist in newer versions of the documentation.

**Comment by jasonvarga** [comment]
We're not using a newer version of Laravel. We will link to 5.1 specifically.

**Comment by jasonvarga** [comment]
I've added a mention of Laravel events, specifically auth.login and auth.logout, which will appear when the rest of the 2.5 docs are merged in.

**Pull request closed without merging**
